/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./src/components/layouts/BaseLayout.vue')['default']
    EditUser: typeof import('./src/components/pages/EditUser.vue')['default']
    Index: typeof import('./src/components/pages/Index.vue')['default']
    Login: typeof import('./src/components/pages/Login.vue')['default']
    Noth: typeof import('./src/components/pages/Noth.vue')['default']
    Register: typeof import('./src/components/pages/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Serach: typeof import('./src/components/pages/Serach.vue')['default']
    SerachResultPage: typeof import('./src/components/pages/SerachResultPage.vue')['default']
    Team: typeof import('./src/components/pages/Team.vue')['default']
    TeamAddPage: typeof import('./src/components/pages/TeamAddPage.vue')['default']
    TeamCardList: typeof import('./src/components/TeamCardList.vue')['default']
    TeamMyCreate: typeof import('./src/components/pages/TeamMyCreate.vue')['default']
    TeamMyJoin: typeof import('./src/components/pages/TeamMyJoin.vue')['default']
    TeamUpdatePage: typeof import('./src/components/pages/TeamUpdatePage.vue')['default']
    User: typeof import('./src/components/pages/User.vue')['default']
    UserCardList: typeof import('./src/components/UserCardList.vue')['default']
    UserUpdate: typeof import('./src/components/pages/UserUpdate.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanStepper: typeof import('vant/es')['Stepper']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanTreeSelect: typeof import('vant/es')['TreeSelect']
  }
}
